### ISSUE TITLE
How to disable all caching

### ISSUE THREAD

**Issue by jelovirt** [xmlresolver/xmlresolver#86]
I'm unable to find documentation on how to disable all caching. Looking at the code, this might not even be supported. So, either please document how to disable caching, or add a feature to to disable it.

**Comment by ndw** [comment]
It was my intent that you could disable caching with the `xml.catalog.cache` property, but there appears to have been some drift. At the API level, you can set the `ResolverFeature.CACHE` to `null` but that doesn't appear to be possible with just configuration properties. How embarrassing.

I'll add an explicit property so that it's clear.
